version: '3.8'

services:
  backend:
    build: ./backend
    container_name: jira-analyzer-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      # Uncomment and add your OpenAI API key if you want to use AI-powered analysis
      # - OPENAI_API_KEY=your_openai_api_key_here
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: jira-analyzer-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped